name: test_ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: 'recursive'
      
    
    # install dependencies
    - name: boost
      run: sudo apt-get update && sudo apt-get install libboost-all-dev
      
    - name: setup solver executable
      working-directory: ${{github.workspace}}/label_gen
      run: |
        bash setup.sh
        
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    
    - name: Install dependencies
      working-directory: ${{github.workspace}}/label_gen
      run: |
        pip install -r requirements.txt
      
    - name: generate_label
      working-directory: ${{github.workspace}}/label_gen/scripts
      run: |
        echo "#for illustrating purpose, we use the smallest map which is empty-8-8"
        python labelgen.py 234 235
        python post_labelgen.py

    
