name: test_macos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    # install dependencies
    - name: boost
      run: brew install boost
      
    - name: Configure CMake
      working-directory: ${{github.workspace}}/feature_gen
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/feature_gen
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/feature_gen/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ./channelgen --map ../random-32-32-20.map --agents ../random-32-32-20-random-1.scen --output ../output/ --agentNumMax 20 --agentNumStep 10

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    
    - name: Install dependencies
      working-directory: ${{github.workspace}}/feature_gen
      run: |
        pip install -r requirements.txt
    
    - name: Test txt2pt Conversionpython
      working-directory: ${{github.workspace}}/feature_gen
      run: python text2tensor.py
